export const sagaActions = {
  SET_AGE: "SET_AGE",
  RESET_AGE: "RESET_AGE",
  SET_UNITS: "SET_UNITS",
  SET_WOOD: "SET_WOOD",
  SET_FOOD: "SET_FOOD",
  SET_GOLD: "SET_GOLD",
  FILTER: "FILTER",
  DETAIL: "DETAIL",
  TOGGLE_WOOD: "TOGGLE_WOOD",
  TOGGLE_FOOD: "TOGGLE_FOOD",
  TOGGLE_GOLD: "TOGGLE_GOLD"
};
